spring:
  mustache:
    suffix: .html
  profiles:
    active: stomp

  datasource:
    url: jdbc:h2:tcp://localhost/~/study

    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  devtools:
    livereload:
      enabled: true

  jpa:
    # show-sql:

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: FamilyStory.mailservice@gmail.com
    password: myFamily_team6!!
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

viewname:
  chatroom:
    list: /chat2/rooms
    detail: /chat2/room-detail

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace



